CREATE TABLE `T_CUS_RECORD_INFO` (
  `ROW_ID` int(20) unsigned NOT NULL AUTO_INCREMENT,
  `CHANNEL` char(2) NOT NULL DEFAULT '',
  `MCHNTCD` char(15) NOT NULL DEFAULT '',
  `MCHNTNM` varchar(50) NOT NULL DEFAULT '',
  `CUSTOM_TYPE` char(2) NOT NULL DEFAULT '',
  `PAYER_MCHNT_ID` varchar(30) NOT NULL DEFAULT '',
  `PAYER_MCHNT_NM` varchar(50) NOT NULL DEFAULT '',
  `BUSI_PLAT_ID` varchar(30) DEFAULT NULL,
  `GZGJ_MCHNT_CODE` varchar(30) DEFAULT NULL,
  `CREATETM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATETM` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ROW_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=97 DEFAULT CHARSET=utf8 COMMENT='T_CUS_RECORD_INFO表'